### ISSUE TITLE
Issues with Arduino Json library

### ISSUE THREAD

**Issue by dino340** [Qrome/marquee-scroller#56]
Attempting to compile on Arduino IDE 1.8.7 yields this error message:

```Arduino: 1.8.7 (Windows Store 1.8.15.0) (Windows 10), Board: "WeMos D1 R1, 80 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

sketch\GeoNamesClient.cpp: In member function 'float GeoNamesClient::getTimeOffset()':

GeoNamesClient.cpp:80:3: error: 'DynamicJsonBuffer' was not declared in this scope

   DynamicJsonBuffer json_buf;

   ^

GeoNamesClient.cpp:80:21: error: expected ';' before 'json_buf'

   DynamicJsonBuffer json_buf;

                     ^

GeoNamesClient.cpp:81:22: error: 'json_buf' was not declared in this scope

   JsonObject& root = json_buf.parseObject(jsonArray);

                      ^

sketch\OctoPrintClient.cpp: In member function 'void OctoPrintClient::getPrinterJobResults()':

OctoPrintClient.cpp:114:3: error: 'DynamicJsonBuffer' was not declared in this scope

   DynamicJsonBuffer jsonBuffer(bufferSize);

   ^

OctoPrintClient.cpp:114:21: error: expected ';' before 'jsonBuffer'

   DynamicJsonBuffer jsonBuffer(bufferSize);

                     ^

OctoPrintClient.cpp:117:22: error: 'jsonBuffer' was not declared in this scope

   JsonObject& root = jsonBuffer.parseObject(printClient);

                      ^

OctoPrintClient.cpp:118:13: error: 'class ArduinoJson650_0_0::JsonObject' has no member named 'success'

   if (!root.success()) {

             ^

sketch\OpenWeatherMapClient.cpp: In member function 'void OpenWeatherMapClient::updateWeather()':

OpenWeatherMapClient.cpp:81:3: error: 'DynamicJsonBuffer' was not declared in this scope

   DynamicJsonBuffer jsonBuffer(bufferSize);

   ^

OpenWeatherMapClient.cpp:81:21: error: expected ';' before 'jsonBuffer'

   DynamicJsonBuffer jsonBuffer(bufferSize);

                     ^

OpenWeatherMapClient.cpp:84:22: error: 'jsonBuffer' was not declared in this scope

   JsonObject& root = jsonBuffer.parseObject(weatherClient);

                      ^

OpenWeatherMapClient.cpp:85:13: error: 'class ArduinoJson650_0_0::JsonObject' has no member named 'success'

   if (!root.success()) {

             ^

OpenWeatherMapClient.cpp:93:12: error: 'class ArduinoJson650_0_0::JsonObject' has no member named 'measureLength'

   if (root.measureLength() <= 150) {

            ^

OpenWeatherMapClient.cpp:94:86: error: 'class ArduinoJson650_0_0::JsonObject' has no member named 'measureLength'

     Serial.println("Error Does not look like we got the data.  Size: " + String(root.measureLength()));

                                                                                      ^

sketch\BitcoinApiClient.cpp: In member function 'void BitcoinApiClient::updateBitcoinData(String)':

BitcoinApiClient.cpp:92:3: error: 'DynamicJsonBuffer' was not declared in this scope

   DynamicJsonBuffer json_buf;

   ^

BitcoinApiClient.cpp:92:21: error: expected ';' before 'json_buf'

   DynamicJsonBuffer json_buf;

                     ^

BitcoinApiClient.cpp:93:22: error: 'json_buf' was not declared in this scope

   JsonObject& root = json_buf.parseObject(jsonArray);

                      ^

BitcoinApiClient.cpp:95:13: error: 'class ArduinoJson650_0_0::JsonObject' has no member named 'success'

   if (!root.success()) {

             ^

exit status 1
'DynamicJsonBuffer' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

```

**Comment by Qrome** [comment]
This is addressed in the README.md file.  You are using a beta version of ArduinoJson -- you need to use the 5.13.X version.

**Comment by dino340** [comment]
Thank you for the quick response, this was indeed the case, I didn't realize I was running the beta version of the ArduinoJson, reverted and it compiled :D
