### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by Neeraj-Ch** [Qrome/marquee-scroller#101]
Arduino: 1.8.7 (Windows 10), Board: "WeMos D1 mini Pro, 160 MHz, 16M (15M SPIFFS), v2 Lower Memory, Disabled, None, All Flash Contents, 921600"

C:\Program Files\Arduino\libraries\Time-master\DateStrings.cpp: In function 'char* monthStr(uint8_t)':

C:\Program Files\Arduino\libraries\Time-master\DateStrings.cpp:76:66: error: 'strcpy_P' was not declared in this scope

     strcpy_P(buffer, (PGM_P)pgm_read_word(&(monthNames_P[month])));

                                                                  ^

C:\Program Files\Arduino\libraries\Time-master\DateStrings.cpp: In function 'char* dayStr(uint8_t)':

C:\Program Files\Arduino\libraries\Time-master\DateStrings.cpp:90:61: error: 'strcpy_P' was not declared in this scope

    strcpy_P(buffer, (PGM_P)pgm_read_word(&(dayNames_P[day])));

                                                             ^

exit status 1
Error compiling for board WeMos D1 mini Pro.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Qrome** [comment]
Make sure you have the latest ESP8266 core board library installed.  2.4.1 or later.  I am using 2.5.0.

**Comment by Neeraj-Ch** [comment]
Still same error. Please provide me link of ESP8266 Core library. 
I think there may be problem with Time-Master Library. 
Please Help

**Comment by Qrome** [comment]
You update the ESP8266 through the Arduino IDE -->  Tools --> Board --> Board Manager...

From there search up the ESP8266 and you can see what version you have installed.   Make sure it is 2.41 or higher.  I am using the latest 2.5.0.

**Comment by Neeraj-Ch** [comment]
Still Not working.....
Maybe Problem is with TimeLib.h
as far as i can Think.



Arduino: 1.8.7 (Windows 10), Board: "WeMos D1 R2 & mini, 160 MHz, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, All Flash Contents, 921600"

C:\Users\Nitin\Downloads\Compressed\libraries\Time-master\DateStrings.cpp: In function 'char* monthStr(uint8_t)':

C:\Users\Nitin\Downloads\Compressed\libraries\Time-master\DateStrings.cpp:76:66: error: 'strcpy_P' was not declared in this scope

     strcpy_P(buffer, (PGM_P)pgm_read_word(&(monthNames_P[month])));

                                                                  ^

C:\Users\Nitin\Downloads\Compressed\libraries\Time-master\DateStrings.cpp: In function 'char* dayStr(uint8_t)':

C:\Users\Nitin\Downloads\Compressed\libraries\Time-master\DateStrings.cpp:90:61: error: 'strcpy_P' was not declared in this scope

    strcpy_P(buffer, (PGM_P)pgm_read_word(&(dayNames_P[day])));

                                                             ^

exit status 1
Error compiling for board WeMos D1 R2 & mini.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Qrome** [comment]
No, there isn't an issue with the code.   Can you tell me what version of ESP8266 core you have loaded? 
![Capture](https://user-images.githubusercontent.com/32021227/54496458-c64caf80-48ac-11e9-9551-7264d9e84dcd.JPG)

**Comment by davericher** [comment]
2.5 is broken, plethora of wifi issues (confirmed by testing wifi again on 2.4)
2.4 does not allow time to compile properly

id est, u broke a lot of clocks

**Comment by Qrome** [comment]
Load the compiled clock bin via the web interface..  We have not seen any wifi issue at all with the latest build using esp8266 core 2.5.0 -- if you have errors with the clock compiling with core 2.5.0, then please share them.

**Comment by magnum129** [comment]
Try selecting "Wemos D1 R1" rather than "WeMos D1 R2 & mini", and try to compile.

**Comment by Neeraj-Ch** [comment]
IN Real i am using Wemos D1 Mini Pro Module.
Tried all solutions 
Thanks to all 
But **Problem is yet not Solved**
I am still not able to Compile for any board type.



Arduino: 1.8.7 (Windows 10), Board: "LOLIN(WEMOS) D1 R2 & mini, 160 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, All Flash Contents, 921600"

C:\Program Files\Arduino\libraries\Time-master\DateStrings.cpp: In function 'char* monthStr(uint8_t)':

C:\Program Files\Arduino\libraries\Time-master\DateStrings.cpp:76:66: error: 'strcpy_P' was not declared in this scope

     strcpy_P(buffer, (PGM_P)pgm_read_word(&(monthNames_P[month])));

                                                                  ^

C:\Program Files\Arduino\libraries\Time-master\DateStrings.cpp: In function 'char* dayStr(uint8_t)':

C:\Program Files\Arduino\libraries\Time-master\DateStrings.cpp:90:61: error: 'strcpy_P' was not declared in this scope

    strcpy_P(buffer, (PGM_P)pgm_read_word(&(dayNames_P[day])));

                                                             ^

exit status 1
Error compiling for board LOLIN(WEMOS) D1 R2 & mini.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by magnum129** [comment]
Did a clean install of Arduino IDE and the esp8266 2.5 and associated libs, on a clean VM, and it compiled. I think it's something with your build environment. Try removing the esp8266 board stuff and reinstalling it via the boards manger.

**Comment by Qrome** [comment]
Yeah, I think he is not running the ESP8266 2.5.0 core.   @Neeraj-Ch -- please confirm as that error you are getting indicates it is NOT 2.5.0.

**Comment by Neeraj-Ch** [comment]
Hi. You are correct. Qrome. Everything just worked fine. Thanks for your support.

**Comment by mdede439** [comment]
I get the same error described here using ESP8266 lib ver 2.4.2.  if I upgrade the to 2.5 I get errors on another library as described here https://github.com/SandboxElectronics/LoRaGoDOCK-Gateway/issues/7.  I have to downgrade to 2.4.2. I did try a clean install but still the conflict.

**Comment by Qrome** [comment]
What board are you selecting when using 2.5.0 and Do you have SPIFFS 1M selected?

Can you give me the actual error you see when using 2.5.0 core?   The link does not seem to be helpful at all.

**Comment by mdede439** [comment]
I actually never looked at the 4M(1M SPIFFS) before.  I did test my situation with and without selecting that and it does give me the same errors during the compile. When I use the 2.5.0 Core I get one set of errors and when I use the 2.4.2 I get another.  This is what I get with 2.5.0.  I will cut and paste a few of them because the verbose setting pumps out a lot of information.

Using board 'd1' from platform in folder: C:\Users\Harley\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0
Using core 'esp8266' from platform in folder: C:\Users\Harley\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0

C:\Users\Harley\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266/WString.h:152:18: note: String& String::operator+=(double)

         String & operator +=(double num) {

                  ^

C:\Users\Harley\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266/WString.h:156:18: note: String& String::operator+=(const __FlashStringHelper*) <near match>

         String & operator += (const __FlashStringHelper *str){

                  ^

C:\Users\Harley\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266/WString.h:156:18: note:   no known conversion for argument 1 from 'IPAddress' to 'const __FlashStringHelper*'

Using library SPI at version 1.0 in folder: C:\Users\Harley\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\SPI 
Using library ESP8266WiFi at version 1.0 in folder: C:\Users\Harley\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\ESP8266WiFi 
Using library ArduinoOTA at version 1.0 in folder: C:\Users\Harley\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\ArduinoOTA 
Using library ESP8266WebServer at version 1.0 in folder: C:\Users\Harley\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\ESP8266WebServer 
Using library Time-master at version 1.5 in folder: C:\1Projects\Arduino IDE Sketchbook\libraries\Time-master 
Using library esp8266-oled-ssd1306-master at version 4.0.0 in folder: C:\1Projects\Arduino IDE Sketchbook\libraries\esp8266-oled-ssd1306-master 
Using library Wire at version 1.0 in folder: C:\Users\Harley\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\Wire 
Using library NeoPixelBus-master at version 2.4.4 in folder: C:\1Projects\Arduino IDE Sketchbook\libraries\NeoPixelBus-master 
Using library ESP8266mDNS at version 1.2 in folder: C:\Users\Harley\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\ESP8266mDNS 
exit status 1
ambiguous overload for 'operator+=' (operand types are 'String' and 'IPAddress')

**Comment by magnum129** [comment]
Can you try comping one of the wifi examples too? Something looks weird
because the errors look like they are coming from some of the dependencies.
What versions are you using?

**Comment by Qrome** [comment]
Can you update your Arduino IDE -- it looks like it might be really old.   What version are you using?
Yeah, you have something that is really old.   Update your IDE to the latest, and make sure you have all the correct versions of libraries.

**Comment by mdede439** [comment]
I would agree with you.  Other stock examples do compile with no issue.  When I had my errors I did a search and found this post and the other post that listed my issue exactly.  But I think the other libraries I am using are different but the ones that are causing the errors are the same. There are a few libraries I had to search for and they may not be the same ones the author used.

**Comment by Qrome** [comment]
@mdede439  -- what version is your Arduino IDE?

**Comment by mdede439** [comment]
The Arduino IDE is at 1.8.9.  Just downloaded it.  However I did have 1.8.7 then updated to 1.8.9.  So it was more of an upgrade and not a clean install

**Comment by mdede439** [comment]
I tried a few examples and they all were wifi sketches.  All did compile.

**Comment by Qrome** [comment]
@mdede439 What version is the WifiManager you have?   Also what board are you selecting?

**Comment by mdede439** [comment]
I do not know how to check for the version of wiFi Manager.  

I selected tri the WeMos D1 R1 and the LOLIN(WEMOS) D1 R2 & mini. Both give the same results.  

I am currently going through the additional libraries I had to include to see if they have any effect.

**Comment by mdede439** [comment]
Unless you mean the WIFI library that I am using.  That is the default built-in wifi ver 1.2.7

**Comment by Qrome** [comment]
@mdede439 -- this project uses WifiManager -- to manage the connection to your router.   
https://github.com/tzapu/WiFiManager

Make sure you have all the supported library files listed in the README.md

**Comment by mdede439** [comment]
Not sure what it was but I did another clean install of Arduino IDE and was finally able to get my machine to compile without error.  I appreciate your help.  Thank you.

**Comment by Qrome** [comment]
Thanks for the update.
